name: flutter_application_manachyna_kusa_2_0
description: Aplicación multiservicio para la provincia de Napo, Ecuador
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  path_provider: ^2.1.2
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  permission_handler: ^12.0.0+1
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2 
  file_picker: ^8.0.0+1  
  image: ^4.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
