// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```çç
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ9kfThOPtGPYGhgNvD8n9fdNdERJ0AmM',
    appId: '1:832653619760:web:5b955e3cc8ef62218133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    authDomain: 'manachynakusa.firebaseapp.com',
    storageBucket: 'manachynakusa.firebasestorage.app',
    measurementId: 'G-4NKJPSS8ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6plAIDdt112LxH7-nPYUjJfwByngedKw',
    appId: '1:832653619760:android:389478f1f8117bba8133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    storageBucket: 'manachynakusa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtW5_sYtYNH4_wl4N9Q6inDmqCKjuADf4',
    appId: '1:832653619760:ios:330b54358204296e8133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    storageBucket: 'manachynakusa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationManachynaKusa20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtW5_sYtYNH4_wl4N9Q6inDmqCKjuADf4',
    appId: '1:832653619760:ios:330b54358204296e8133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    storageBucket: 'manachynakusa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationManachynaKusa20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ9kfThOPtGPYGhgNvD8n9fdNdERJ0AmM',
    appId: '1:832653619760:web:41758c20d723ef968133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    authDomain: 'manachynakusa.firebaseapp.com',
    storageBucket: 'manachynakusa.firebasestorage.app',
    measurementId: 'G-W0DC3SWGYD',
  );
}
