// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ9kfThOPtGPYGhgNvD8n9fdNdERJ0AmM',
    appId: '1:832653619760:web:84a4aa6bd1ff8c258133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    authDomain: 'manachynakusa.firebaseapp.com',
    databaseURL: 'https://manachynakusa-default-rtdb.firebaseio.com',
    storageBucket: 'manachynakusa.firebasestorage.app',
    measurementId: 'G-32VPSK0W54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6plAIDdt112LxH7-nPYUjJfwByngedKw',
    appId: '1:832653619760:android:4c676b9c0eb8aabe8133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    databaseURL: 'https://manachynakusa-default-rtdb.firebaseio.com',
    storageBucket: 'manachynakusa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtW5_sYtYNH4_wl4N9Q6inDmqCKjuADf4',
    appId: '1:832653619760:ios:4fa5ed065c8079458133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    databaseURL: 'https://manachynakusa-default-rtdb.firebaseio.com',
    storageBucket: 'manachynakusa.firebasestorage.app',
    iosClientId: '832653619760-vir18fdgpretg24tp8lpepillrol5cte.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationManachynaKusa20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtW5_sYtYNH4_wl4N9Q6inDmqCKjuADf4',
    appId: '1:832653619760:ios:4fa5ed065c8079458133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    databaseURL: 'https://manachynakusa-default-rtdb.firebaseio.com',
    storageBucket: 'manachynakusa.firebasestorage.app',
    iosClientId: '832653619760-vir18fdgpretg24tp8lpepillrol5cte.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationManachynaKusa20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ9kfThOPtGPYGhgNvD8n9fdNdERJ0AmM',
    appId: '1:832653619760:web:341a76bbaf25fb688133f5',
    messagingSenderId: '832653619760',
    projectId: 'manachynakusa',
    authDomain: 'manachynakusa.firebaseapp.com',
    databaseURL: 'https://manachynakusa-default-rtdb.firebaseio.com',
    storageBucket: 'manachynakusa.firebasestorage.app',
    measurementId: 'G-QGL0N53SQ7',
  );
}
